### ISSUE TITLE
BinDebug

### ISSUE THREAD

**Issue by fml508** [fml508/QRcodeGenerator#2]
-restucture where will the python script be,
-also "find" a new place to the generated QR codes 
-(These'll require rewriting (some of) the **qcode.py** and the **Form1.cs**.

**Comment by thetruekys** [comment]
### Brainstorming

> -restucture where will the python script be. 

- [inside the main folder create two subfolders. One named **Script**, and an other named **QRcodes**] 

> -(These'll require rewriting (some of) the **qcode.py** and the **Form1.cs.)**

- [ I belive the only change we'll need to do (for this specific problem per se) is to _Repoint_  the **Form1.cs** to the new **Script** folder, and in the **qcode.py** we'll route it to the **Qrcodes** folder.]
